import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
// Loading animation
var shimmer = "before:absolute before:inset-0 before:-translate-x-full before:animate-[shimmer_2s_infinite] before:bg-gradient-to-r before:from-transparent before:via-white/60 before:to-transparent";
export function CardSkeleton() {
    return (_jsxs("div", { className: "".concat(shimmer, " relative overflow-hidden rounded-xl bg-gray-100 p-2 shadow-sm"), children: [_jsxs("div", { className: "flex p-4", children: [_jsx("div", { className: "h-5 w-5 rounded-md bg-gray-200" }), _jsx("div", { className: "ml-2 h-6 w-16 rounded-md bg-gray-200 text-sm font-medium" })] }), _jsx("div", { className: "flex items-center justify-center truncate rounded-xl bg-white px-4 py-8", children: _jsx("div", { className: "h-7 w-20 rounded-md bg-gray-200" }) })] }));
}
export function CardsSkeleton() {
    return (_jsxs(_Fragment, { children: [_jsx(CardSkeleton, {}), _jsx(CardSkeleton, {}), _jsx(CardSkeleton, {}), _jsx(CardSkeleton, {})] }));
}
export function RevenueChartSkeleton() {
    return (_jsxs("div", { className: "".concat(shimmer, " relative w-full overflow-hidden md:col-span-4"), children: [_jsx("div", { className: "mb-4 h-8 w-36 rounded-md bg-gray-100" }), _jsxs("div", { className: "rounded-xl bg-gray-100 p-4", children: [_jsx("div", { className: "sm:grid-cols-13 mt-0 grid h-[410px] grid-cols-12 items-end gap-2 rounded-md  bg-white p-4 md:gap-4" }), _jsxs("div", { className: "flex items-center pb-2 pt-6", children: [_jsx("div", { className: "h-5 w-5 rounded-full bg-gray-200" }), _jsx("div", { className: "ml-2 h-4 w-20 rounded-md bg-gray-200" })] })] })] }));
}
export function InvoiceSkeleton() {
    return (_jsxs("div", { className: "flex flex-row items-center justify-between border-b border-gray-100 py-4", children: [_jsxs("div", { className: "flex items-center", children: [_jsx("div", { className: "mr-2 h-8 w-8 rounded-full bg-gray-200" }), _jsxs("div", { className: "min-w-0", children: [_jsx("div", { className: "h-5 w-40 rounded-md bg-gray-200" }), _jsx("div", { className: "mt-2 h-4 w-12 rounded-md bg-gray-200" })] })] }), _jsx("div", { className: "mt-2 h-4 w-12 rounded-md bg-gray-200" })] }));
}
export function LatestInvoicesSkeleton() {
    return (_jsxs("div", { className: "".concat(shimmer, " relative flex w-full flex-col overflow-hidden md:col-span-4 lg:col-span-4"), children: [_jsx("div", { className: "mb-4 h-8 w-36 rounded-md bg-gray-100" }), _jsx("div", { className: "flex grow flex-col justify-between rounded-xl bg-gray-100 p-4", children: _jsxs("div", { className: "bg-white px-6", children: [_jsx(InvoiceSkeleton, {}), _jsx(InvoiceSkeleton, {}), _jsx(InvoiceSkeleton, {}), _jsx(InvoiceSkeleton, {}), _jsx(InvoiceSkeleton, {}), _jsxs("div", { className: "flex items-center pb-2 pt-6", children: [_jsx("div", { className: "h-5 w-5 rounded-full bg-gray-200" }), _jsx("div", { className: "ml-2 h-4 w-20 rounded-md bg-gray-200" })] })] }) })] }));
}
export default function DashboardSkeleton(_a) {
    var noTop = _a.noTop;
    return (_jsxs(_Fragment, { children: [!noTop && (_jsx("div", { className: "".concat(shimmer, " relative mb-4 h-8 w-36 overflow-hidden rounded-md bg-gray-100") })), _jsxs("div", { className: "grid gap-6 sm:grid-cols-2 lg:grid-cols-4", children: [_jsx(CardSkeleton, {}), _jsx(CardSkeleton, {}), _jsx(CardSkeleton, {}), _jsx(CardSkeleton, {})] }), _jsxs("div", { className: "mt-6 grid grid-cols-1 gap-6 md:grid-cols-4 lg:grid-cols-8", children: [_jsx("div", { className: "col-span-full md:col-span-3 lg:col-span-6", children: _jsx(RevenueChartSkeleton, {}) }), _jsx("div", { className: "col-span-full md:col-span-1 lg:col-span-2", children: _jsx(LatestInvoicesSkeleton, {}) })] })] }));
}
export function TitleSkeleton() {
    return (_jsx("div", { className: "".concat(shimmer, " relative mb-4 h-8 w-36 overflow-hidden rounded-md bg-gray-100") }));
}
export function TableRowSkeleton() {
    return (_jsxs("tr", { className: "w-full border-b border-gray-100 last-of-type:border-none [&:first-child>td:first-child]:rounded-tl-lg [&:first-child>td:last-child]:rounded-tr-lg [&:last-child>td:first-child]:rounded-bl-lg [&:last-child>td:last-child]:rounded-br-lg", children: [_jsx("td", { className: "relative overflow-hidden whitespace-nowrap py-3 pl-6 pr-3", children: _jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: "h-8 w-8 rounded-full bg-gray-100" }), _jsx("div", { className: "h-6 w-24 rounded bg-gray-100" })] }) }), _jsx("td", { className: "whitespace-nowrap px-3 py-3", children: _jsx("div", { className: "h-6 w-32 rounded bg-gray-100" }) }), _jsx("td", { className: "whitespace-nowrap px-3 py-3", children: _jsx("div", { className: "h-6 w-16 rounded bg-gray-100" }) }), _jsx("td", { className: "whitespace-nowrap px-3 py-3", children: _jsx("div", { className: "h-6 w-16 rounded bg-gray-100" }) }), _jsx("td", { className: "whitespace-nowrap py-3 pl-6 pr-3", children: _jsxs("div", { className: "flex justify-end gap-3", children: [_jsx("div", { className: "h-[38px] w-[38px] rounded bg-gray-100" }), _jsx("div", { className: "h-[38px] w-[38px] rounded bg-gray-100" })] }) })] }));
}
export function InvoicesMobileSkeleton() {
    return (_jsxs("div", { className: "mb-2 w-full rounded-md bg-white p-4", children: [_jsxs("div", { className: "flex items-center justify-between border-b border-gray-100 pb-8", children: [_jsxs("div", { className: "flex items-center", children: [_jsx("div", { className: "mr-2 h-8 w-8 rounded-full bg-gray-100" }), _jsx("div", { className: "h-6 w-16 rounded bg-gray-100" })] }), _jsx("div", { className: "h-6 w-16 rounded bg-gray-100" })] }), _jsxs("div", { className: "flex w-full items-center justify-between pt-4", children: [_jsxs("div", { children: [_jsx("div", { className: "h-6 w-16 rounded bg-gray-100" }), _jsx("div", { className: "mt-2 h-6 w-24 rounded bg-gray-100" })] }), _jsxs("div", { className: "flex justify-end gap-2", children: [_jsx("div", { className: "h-10 w-10 rounded bg-gray-100" }), _jsx("div", { className: "h-10 w-10 rounded bg-gray-100" })] })] })] }));
}
export function InvoicesTableSkeleton() {
    return (_jsx("div", { className: "mt-6 flow-root", children: _jsx("div", { className: "inline-block min-w-full align-middle", children: _jsxs("div", { className: "rounded-lg bg-gray-50 p-2 md:pt-0", children: [_jsxs("div", { className: "md:hidden", children: [_jsx(InvoicesMobileSkeleton, {}), _jsx(InvoicesMobileSkeleton, {}), _jsx(InvoicesMobileSkeleton, {}), _jsx(InvoicesMobileSkeleton, {}), _jsx(InvoicesMobileSkeleton, {}), _jsx(InvoicesMobileSkeleton, {})] }), _jsxs("table", { className: "hidden min-w-full text-gray-900 md:table", children: [_jsx("thead", { className: "rounded-lg text-left text-sm font-normal", children: _jsxs("tr", { children: [_jsx("th", { scope: "col", className: "px-4 py-5 font-medium sm:pl-6", children: "Customer" }), _jsx("th", { scope: "col", className: "px-3 py-5 font-medium", children: "Email" }), _jsx("th", { scope: "col", className: "px-3 py-5 font-medium", children: "Amount" }), _jsx("th", { scope: "col", className: "px-3 py-5 font-medium", children: "Date" }), _jsx("th", { scope: "col", className: "px-3 py-5 font-medium", children: "Status" }), _jsx("th", { scope: "col", className: "relative pb-4 pl-3 pr-6 pt-2 sm:pr-6", children: _jsx("span", { className: "sr-only", children: "Edit" }) })] }) }), _jsxs("tbody", { className: "bg-white", children: [_jsx(TableRowSkeleton, {}), _jsx(TableRowSkeleton, {}), _jsx(TableRowSkeleton, {}), _jsx(TableRowSkeleton, {}), _jsx(TableRowSkeleton, {}), _jsx(TableRowSkeleton, {})] })] })] }) }) }));
}
export function TableSkeleton() {
    return (_jsx("div", { className: "mt-6 flow-root", children: _jsx("div", { className: "inline-block min-w-full align-middle", children: _jsxs("div", { className: "rounded-lg bg-gray-50  md:pt-0", children: [_jsxs("div", { className: "md:hidden", children: [_jsx(InvoicesMobileSkeleton, {}), _jsx(InvoicesMobileSkeleton, {}), _jsx(InvoicesMobileSkeleton, {}), _jsx(InvoicesMobileSkeleton, {}), _jsx(InvoicesMobileSkeleton, {}), _jsx(InvoicesMobileSkeleton, {})] }), _jsx("table", { className: "hidden min-w-full text-gray-900 md:table", children: _jsxs("tbody", { className: "bg-white", children: [_jsx(TableRowSkeleton, {}), _jsx(TableRowSkeleton, {}), _jsx(TableRowSkeleton, {}), _jsx(TableRowSkeleton, {}), _jsx(TableRowSkeleton, {}), _jsx(TableRowSkeleton, {})] }) })] }) }) }));
}
